version: '3'

services:

  sqlite3:
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data1:/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data