version: '3'

services:

  sqlite3:
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data1:/data
    ports:
      - "5432:5432"

#  mariadb:
#    image: mariadb
#    environment:
#      - MYSQL_ROOT_PASSWORD=mysecretpassword
#      - MYSQL_DATABASE=mydatabase
#      - MYSQL_USER=myuser
#      - MYSQL_PASSWORD=mypassword
#    volumes:
#      - ./data:/var/lib/mysql
#    ports:
#      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data